module.exports = {
  TITLE_SECTIONS_COUNT: 3,
  DEFAULT_TYPE_TAG: 'feat',
  WRAP_SETTINGS: Object.freeze({
    trim: true,
    indent: '',
    width: 100,
  }),
  TYPES: Object.freeze({
    message: Symbol('message'),
    title: Symbol('title'),
    body: Symbol('body'),
    section: Symbol('section'),
    text: Symbol('text'),
    fix: Symbol('text'),
  }),
  FIX_KEYWORDS: [
    'close',
    'closes',
    'closed',
    'Close',
    'Closed',
    'Closes',
    'fix',
    'fixes',
    'fixed',
    'Fix',
    'Fixes',
    'Fixed',
  ],
};
